# Generated by Django 2.0.5 on 2018-05-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180523_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='height',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Длина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='width',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Высота'),
            preserve_default=False,
        ),
    ]
